SELECT map(array[0,
           1,
           2,
           3,
           4,
           5,
           6,
           7,
           8,
           9,
           10,
           11,
           12,
           13,
           14,
           15,
           16,
           17,
           18,
           19,
           20,
           21,
           22,
           23,
           24,
           25,
           26,
           27,
           28,
           29,
           30,
           31,
           32,
           33,
           34,
           35,
           36,
           37,
           38],
           array[cast(from_big_endian_64(xxhash64(to_utf8(cast(c_customer_id as varchar)))) as decimal(38, 0)),
           cast(from_big_endian_64(xxhash64(to_utf8(cast(c_salutation as varchar)))) as decimal(38, 0)),
           cast(from_big_endian_64(xxhash64(to_utf8(cast(c_first_name as varchar)))) as decimal(38, 0)),
           cast(from_big_endian_64(xxhash64(to_utf8(cast(c_last_name as varchar)))) as decimal(38, 0)),
           cast(from_big_endian_64(xxhash64(to_utf8(cast(c_preferred_cust_flag as varchar)))) as decimal(38, 0)),
           cast(c_birth_day as decimal(38, 0)),
           cast(c_birth_month as decimal(38, 0)),
           cast(c_birth_year as decimal(38, 0)),
           cast(from_big_endian_64(xxhash64(to_utf8(cast(c_birth_country as varchar)))) as decimal(38, 0)),
           cast(from_big_endian_64(xxhash64(to_utf8(cast(c_login as varchar)))) as decimal(38, 0)),
           cast(from_big_endian_64(xxhash64(to_utf8(cast(c_email_address as varchar)))) as decimal(38, 0)),
           cast(wr_order_number as decimal(38, 0)),
           cast(wr_return_quantity as decimal(38, 0)),
           cast(wr_return_amt as decimal(38, 0)),
           cast(wr_return_tax as decimal(38, 0)),
           cast(wr_return_amt_inc_tax as decimal(38, 0)),
           cast(wr_fee as decimal(38, 0)),
           cast(wr_return_ship_cost as decimal(38, 0)),
           cast(wr_refunded_cash as decimal(38, 0)),
           cast(wr_reversed_charge as decimal(38, 0)),
           cast(wr_account_credit as decimal(38, 0)),
           cast(wr_net_loss as decimal(38, 0)),
           cast(ws_order_number as decimal(38, 0)),
           cast(ws_quantity as decimal(38, 0)),
           cast(ws_wholesale_cost as decimal(38, 0)),
           cast(ws_list_price as decimal(38, 0)),
           cast(ws_sales_price as decimal(38, 0)),
           cast(ws_ext_discount_amt as decimal(38, 0)),
           cast(ws_ext_sales_price as decimal(38, 0)),
           cast(ws_ext_wholesale_cost as decimal(38, 0)),
           cast(ws_ext_list_price as decimal(38, 0)),
           cast(ws_ext_tax as decimal(38, 0)),
           cast(ws_coupon_amt as decimal(38, 0)),
           cast(ws_ext_ship_cost as decimal(38, 0)),
           cast(ws_net_paid as decimal(38, 0)),
           cast(ws_net_paid_inc_tax as decimal(38, 0)),
           cast(ws_net_paid_inc_ship as decimal(38, 0)),
           cast(ws_net_paid_inc_ship_tax as decimal(38, 0)),
           cast(ws_net_profit as decimal(38, 0))]) as test
FROM   customer, web_returns, web_sales
WHERE  (web_sales.ws_bill_customer_sk = customer.c_customer_sk
   and (web_sales.ws_bill_customer_sk = web_returns.wr_refunded_customer_sk
    or web_sales.ws_bill_customer_sk = web_returns.wr_returning_customer_sk));