CREATE TABLE if not exists bf_sparse_order_bt_3_tables with (format = 'PARQUET') AS
SELECT map(array[0,
           1,
           2,
           3,
           4,
           5,
           6,
           7,
           8,
           9,
           10,
           11,
           12,
           13,
           14,
           15,
           16,
           17,
           18,
           19,
           20,
           21,
           22,
           23,
           24,
           25,
           26,
           27,
           28,
           29,
           30,
           31,
           32,
           33,
           34,
           35,
           36,
           37,
           38,
           39,
           40,
           41,
           42,
           43,
           44,
           45,
           46,
           47,
           48,
           49,
           50,
           51,
           52,
           53,
           54,
           55,
           56,
           57,
           58,
           59,
           60,
           61,
           62,
           63,
           64,
           65,
           66,
           67,
           68,
           69,
           70,
           71,
           72,
           73,
           74,
           75,
           76,
           77,
           78,
           79,
           80,
           81,
           82,
           83,
           84,
           85,
           86,
           87,
           88,
           89,
           90,
           91,
           92,
           93,
           94,
           95,
           96,
           97,
           98,
           99,
           100,
           101,
           102,
           103,
           104,
           105,
           106,
           107,
           108,
           109,
           110,
           111,
           112,
           113],
           array[max_by(cast(i_item_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(i_item_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_item_id as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_item_id as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_item_desc as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_item_desc as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(i_current_price as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(i_current_price as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(i_brand_id as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(i_brand_id as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_brand as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_brand as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(i_class_id as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(i_class_id as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_class as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_class as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(i_category_id as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(i_category_id as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_category as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_category as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(i_manufact_id as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(i_manufact_id as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_manufact as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_manufact as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_size as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_size as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_formulation as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_formulation as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_color as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_color as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_units as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_units as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_container as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_container as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(i_manager_id as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(i_manager_id as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_product_name as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_product_name as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(cl_customer_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(cl_customer_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(cl_item_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(cl_item_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(cl_session_id as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(cl_session_id as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(cl_action as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(cl_action as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_sold_date_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_sold_date_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_sold_time_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_sold_time_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_ship_date_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_ship_date_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_item_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_item_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_bill_customer_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_bill_customer_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_bill_cdemo_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_bill_cdemo_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_bill_hdemo_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_bill_hdemo_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_bill_addr_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_bill_addr_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_ship_customer_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_ship_customer_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_ship_cdemo_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_ship_cdemo_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_ship_hdemo_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_ship_hdemo_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_ship_addr_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_ship_addr_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_web_page_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_web_page_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_web_site_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_web_site_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_ship_mode_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_ship_mode_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_warehouse_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_warehouse_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_promo_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_promo_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_order_number as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_order_number as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_quantity as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_quantity as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_wholesale_cost as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_wholesale_cost as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_list_price as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_list_price as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_sales_price as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_sales_price as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_ext_discount_amt as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_ext_discount_amt as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_ext_sales_price as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_ext_sales_price as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_ext_wholesale_cost as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_ext_wholesale_cost as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_ext_list_price as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_ext_list_price as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_ext_tax as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_ext_tax as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_coupon_amt as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_coupon_amt as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_ext_ship_cost as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_ext_ship_cost as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_net_paid as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_net_paid as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_net_paid_inc_tax as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_net_paid_inc_tax as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_net_paid_inc_ship as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_net_paid_inc_ship as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_net_paid_inc_ship_tax as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_net_paid_inc_ship_tax as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(ws_net_profit as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(ws_net_profit as decimal(38, 0)), i_wholesale_cost, 5)]) as feature_map
FROM   item, click_log_formatted, web_sales
WHERE  (cl_item_sk = i_item_sk
   and ws_item_sk = cl_item_sk)
GROUP BY cl_customer_sk, cl_session_id;