CREATE TABLE if not exists bf_sparse_order_bt_2_tables with (format = 'PARQUET') AS
SELECT map(array[0,
           1,
           2,
           3,
           4,
           5,
           6,
           7,
           8,
           9,
           10,
           11,
           12,
           13,
           14,
           15,
           16,
           17,
           18,
           19,
           20,
           21,
           22,
           23,
           24,
           25,
           26,
           27,
           28,
           29,
           30,
           31,
           32,
           33,
           34,
           35,
           36,
           37,
           38,
           39,
           40,
           41,
           42,
           43,
           44,
           45],
           array[max_by(cast(i_item_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(i_item_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_item_id as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_item_id as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_item_desc as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_item_desc as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(i_current_price as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(i_current_price as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(i_brand_id as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(i_brand_id as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_brand as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_brand as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(i_class_id as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(i_class_id as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_class as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_class as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(i_category_id as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(i_category_id as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_category as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_category as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(i_manufact_id as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(i_manufact_id as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_manufact as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_manufact as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_size as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_size as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_formulation as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_formulation as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_color as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_color as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_units as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_units as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_container as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_container as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(i_manager_id as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(i_manager_id as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_product_name as varchar)))) as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(from_big_endian_64(xxhash64(to_utf8(cast(i_product_name as varchar)))) as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(cl_customer_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(cl_customer_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(cl_item_sk as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(cl_item_sk as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(cl_session_id as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(cl_session_id as decimal(38, 0)), i_wholesale_cost, 5),
           max_by(cast(cl_action as decimal(38, 0)), cl_action_date*86400+cl_action_time, 10),
           min_by(cast(cl_action as decimal(38, 0)), i_wholesale_cost, 5)]) as feature_map
FROM   item, click_log_formatted
WHERE  cl_item_sk = i_item_sk
GROUP BY cl_customer_sk, cl_session_id;